>>> 2012-12-21T13:03:25-0200
poo.sca.SCARuntimeException: numero menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:145)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2012-12-21T13:03:33-0200
poo.sca.SCARuntimeException: numero menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:156)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2012-12-21T13:03:33-0200
poo.sca.SCARuntimeException: Erro de entrada do usuario
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:135)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:156)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2012-12-21T13:03:44-0200
poo.sca.SCARuntimeException: numero menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:145)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2012-12-21T13:04:34-0200
poo.sca.SCARuntimeException: numero menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:145)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2012-12-21T13:04:40-0200
poo.sca.SCARuntimeException: numero menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:156)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2012-12-21T13:04:40-0200
poo.sca.SCARuntimeException: Erro de entrada do usuario
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:135)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:156)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2012-12-21T13:09:15-0200
poo.sca.SCARuntimeException: Nao existe turma com esse numero
	at poo.sca.SCAFacade.verDetalhes(SCAFacade.java:370)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:241)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2012-12-21T13:09:21-0200
poo.sca.SCARuntimeException: Nao existe turma com esse numero
	at poo.sca.SCAFacade.verDetalhes(SCAFacade.java:370)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:241)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:43:50-0200
poo.sca.SCAException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:121)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:145)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:44:06-0200
poo.sca.SCAException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:121)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:145)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:44:41-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:156)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:44:41-0200
poo.sca.SCARuntimeException: Erro de entrada do usuario
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:135)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:156)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:46:23-0200
poo.sca.SCARuntimeException: Nome da Disciplina é invalido: 
	at poo.sca.Disciplina.setNome(Disciplina.java:27)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:131)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:46:23-0200
poo.sca.SCARuntimeException: Erro de entrada do usuario
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:135)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:50:31-0200
poo.sca.SCARuntimeException: Nome da Disciplina é invalido: 
	at poo.sca.Disciplina.setNome(Disciplina.java:27)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:131)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:50:36-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:50:36-0200
poo.sca.SCARuntimeException: Erro de entrada do usuario
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:135)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:51:10-0200
poo.sca.SCARuntimeException: Nome da Disciplina é invalido: 
	at poo.sca.Disciplina.setNome(Disciplina.java:27)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:131)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:52:19-0200
poo.sca.SCARuntimeException: Nome da Disciplina é invalido: null
	at poo.sca.Disciplina.setNome(Disciplina.java:27)
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:134)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:236)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:52:19-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:236)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:52:19-0200
poo.sca.SCAException: Erro ao ler o arquivo de disciplinas
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:239)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:52:23-0200
poo.sca.SCARuntimeException: Nome da Disciplina é invalido: null
	at poo.sca.Disciplina.setNome(Disciplina.java:27)
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:134)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:236)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:52:23-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:236)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:52:23-0200
poo.sca.SCAException: Erro ao ler o arquivo de disciplinas
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:239)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:53:13-0200
poo.sca.SCARuntimeException: Nome da Disciplina é invalido: null
	at poo.sca.Disciplina.setNome(Disciplina.java:27)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:131)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:53:18-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:53:18-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:135)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:54:03-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:54:03-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:135)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:54:14-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:54:23-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:130)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T00:54:23-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:135)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:01:37-0200
poo.sca.SCARuntimeException: Codigo Invalido
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:128)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:02:59-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:119)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:03:03-0200
poo.sca.SCARuntimeException: Codigo Invalido: 
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:128)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:03:10-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.Disciplina.setCodigo(Disciplina.java:14)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:123)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:03:10-0200
poo.sca.SCARuntimeException: codigo da disciplina menor que 0 ou maior que 99999
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:134)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:153)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:20:45-0200
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:177)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:20:45-0200
poo.sca.SCARuntimeException: Codigo Invalido
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:196)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:20:51-0200
java.lang.NumberFormatException: For input string: "k"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:177)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:20:51-0200
poo.sca.SCARuntimeException: Codigo Invalido
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:196)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:07-0200
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:177)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:07-0200
poo.sca.SCARuntimeException: Codigo Invalido
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:196)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:09-0200
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:177)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:09-0200
poo.sca.SCARuntimeException: Codigo Invalido
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:196)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:43-0200
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:146)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:43-0200
poo.sca.SCARuntimeException: Matricula Invalida
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:162)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:46-0200
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:146)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:46-0200
poo.sca.SCARuntimeException: Matricula Invalida
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:162)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:56-0200
poo.sca.SCARuntimeException: Ja existe professor com essa matricula
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:153)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:21:56-0200
poo.sca.SCARuntimeException: Ja existe professor com essa matricula
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:168)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:03-0200
poo.sca.SCARuntimeException: Ja existe professor com essa matricula
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:153)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:03-0200
poo.sca.SCARuntimeException: Ja existe professor com essa matricula
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:168)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:11-0200
java.lang.NumberFormatException: For input string: "jjl"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:146)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:11-0200
poo.sca.SCARuntimeException: Matricula Invalida
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:162)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:14-0200
java.lang.NumberFormatException: For input string: "kp"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:146)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:14-0200
poo.sca.SCARuntimeException: Matricula Invalida
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:162)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:36-0200
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:177)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:36-0200
poo.sca.SCARuntimeException: Codigo Invalido
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:196)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:40-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarCursos(SCAPersistenciaArquivo.java:258)
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:181)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:40-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarCursos(SCAPersistenciaArquivo.java:267)
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:181)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:40-0200
poo.sca.SCAException: Erro no arquivo
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:193)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:43-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarCursos(SCAPersistenciaArquivo.java:258)
	at poo.sca.SCAFacade.getCursosIterator(SCAFacade.java:239)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:65)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:43-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarCursos(SCAPersistenciaArquivo.java:267)
	at poo.sca.SCAFacade.getCursosIterator(SCAFacade.java:239)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:65)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:22:43-0200
poo.sca.SCAException: Erro ao ler o arquivo cursos
	at poo.sca.SCAFacade.getCursosIterator(SCAFacade.java:242)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:65)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:23:04-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarCursos(SCAPersistenciaArquivo.java:258)
	at poo.sca.SCAFacade.getCursosIterator(SCAFacade.java:239)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:65)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:23:04-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarCursos(SCAPersistenciaArquivo.java:267)
	at poo.sca.SCAFacade.getCursosIterator(SCAFacade.java:239)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:65)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:23:04-0200
poo.sca.SCAException: Erro ao ler o arquivo cursos
	at poo.sca.SCAFacade.getCursosIterator(SCAFacade.java:242)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:65)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:23:26-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.Curso.setNome(Curso.java:20)
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:189)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:23:26-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:199)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:23:37-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.Curso.setNome(Curso.java:20)
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:189)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:23:37-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.SCAFacade.criarCurso(SCAFacade.java:199)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:47)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:42:49-0200
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:146)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:42:49-0200
poo.sca.SCARuntimeException: Matricula Invalida
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:162)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:43:12-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.Professor.setNome(Professor.java:20)
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:158)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:43:12-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:168)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:43:22-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.Professor.setNome(Professor.java:20)
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:158)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:43:22-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:168)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:43:44-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.Professor.setNome(Professor.java:20)
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:158)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:43:44-0200
poo.sca.SCARuntimeException: Nome da Professor é invalido: 
	at poo.sca.SCAFacade.criarProfessor(SCAFacade.java:168)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:43:49-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:248)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:43:49-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:248)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T01:43:49-0200
poo.sca.SCAException: Erro ao ler o arquivo de disciplinas
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:251)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T15:42:13-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:120)
	at poo.sca.DisciplinaTest.testeDisciplina(DisciplinaTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T15:50:47-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeDisciplina(DisciplinaTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T15:50:47-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeDisciplina(DisciplinaTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T15:51:02-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeDisciplina(DisciplinaTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T15:51:02-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeDisciplina(DisciplinaTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T15:51:21-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:120)
	at poo.sca.DisciplinaTest.testeDisciplina(DisciplinaTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T15:52:35-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:120)
	at poo.sca.DisciplinaTest.testeDisciplina(DisciplinaTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T16:11:13-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:120)
	at poo.sca.DisciplinaTest.testeDisciplina(DisciplinaTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T16:20:20-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:120)
	at poo.sca.DisciplinaTest.testeDisciplina(DisciplinaTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T16:29:43-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T16:29:43-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T16:30:16-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T16:30:16-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-11T17:00:59-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:248)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T17:00:59-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:248)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T17:00:59-0200
poo.sca.SCAException: Erro ao ler o arquivo de disciplinas
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:251)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T17:01:07-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:248)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T17:01:07-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:248)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-11T17:01:07-0200
poo.sca.SCAException: Erro ao ler o arquivo de disciplinas
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:251)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:171)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:29:08-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:119)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-16T23:29:36-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:119)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-16T23:29:51-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:119)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-16T23:32:57-0200
java.lang.NumberFormatException: For input string: "´l"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:33:01-0200
java.lang.NumberFormatException: For input string: "khp"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:33:07-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:144)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:33:24-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:144)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:33:39-0200
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:33:40-0200
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:33:42-0200
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:33:44-0200
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:33:46-0200
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:34:33-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:144)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:34:40-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:161)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:34:40-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:132)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:161)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:34:47-0200
java.lang.NumberFormatException: For input string: "fd"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:142)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:49:11-0200
java.lang.NumberFormatException: For input string: "kljkl"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:94)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:49:43-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:149)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:49:46-0200
java.lang.NumberFormatException: For input string: "ojko"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:164)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:49:51-0200
java.lang.NumberFormatException: For input string: "pokjpo"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:147)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:49:54-0200
java.lang.NumberFormatException: For input string: "kp"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:147)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:53:02-0200
java.lang.NumberFormatException: For input string: "kp"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:101)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:53:16-0200
java.lang.NumberFormatException: For input string: "kp"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:101)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-16T23:53:20-0200
java.lang.NumberFormatException: For input string: "ljk"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:101)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:18:10-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:234)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:18:10-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:234)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:18:10-0200
poo.sca.SCAException: Erro ao ler o arquivo de disciplinas
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:237)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:18:12-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:234)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:18:12-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:234)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:18:12-0200
poo.sca.SCAException: Erro ao ler o arquivo de disciplinas
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:237)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:18:22-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:234)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:18:22-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:234)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:18:22-0200
poo.sca.SCAException: Erro ao ler o arquivo de disciplinas
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:237)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:19:35-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:131)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:234)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:19:35-0200
poo.sca.io.SCAPersistenciaException
	at poo.sca.io.SCAPersistenciaArquivo.recuperarDisciplinas(SCAPersistenciaArquivo.java:140)
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:234)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T22:19:35-0200
poo.sca.SCAException: Erro ao ler o arquivo de disciplinas
	at poo.sca.SCAFacade.getDisciplinasIterator(SCAFacade.java:237)
	at poo.sca.ui.SCA.exibirMenu(SCA.java:194)
	at poo.sca.ui.SCA.main(SCA.java:22)
>>> 2013-01-17T23:04:38-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:04:38-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:04:38-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testaDisciplina(DisciplinaTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:11:46-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testaDisciplina(DisciplinaTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:11:46-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:13:15-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:13:18-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:13:18-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testaDisciplina(DisciplinaTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:14:51-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:17:58-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testaDisciplina(DisciplinaTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-17T23:17:58-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCodigo(DisciplinaTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
>>> 2013-01-23T15:47:45-0200
poo.sca.SCARuntimeException: Ja existe disciplina com esse codigo
	at poo.sca.SCAFacade.criarDisciplina(SCAFacade.java:117)
	at poo.sca.DisciplinaTest.testeCriarDisciplina(DisciplinaTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
